### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by DragonMaster14545** [joe-vettek/Fluid-Drawers-Legacy#12] opened 2023-01-31 10:04 UTC
## Game Version, Launcher Version, Mod Version

MC 1.18.2

Forge 36.2.20

Newest beta

## Problem Description

Its the same crash as I already had in Crash #11

## Crash Log

https://pastebin.com/7spex8RL

**Comment by joe-vettek** [comment] 2023-01-31 15:17
The second repair version has been uploaded. This time, a new safety measure has been added. It was a problem with pumping water before, but this time it is a problem with adding water.

**Comment by joe-vettek** [comment] 2023-01-31 15:18
There is no rush to close this issue, you can check the situation first. Because I am busy now, I can only judge by experience.

**Comment by DragonMaster14545** [comment] 2023-01-31 15:50
Ok thanks a lot for your quick reply

**Comment by DragonMaster14545** [comment] 2023-02-02 06:47
https://pastebin.com/WBUqLw2A
Just got this crash

**Comment by DragonMaster14545** [comment] 2023-02-05 17:06
https://pastebin.com/ZCJy287d
Happened again...

**Comment by joe-vettek** [comment] 2023-02-05 17:57
that's a new problem

**Comment by DragonMaster14545** [comment] 2023-02-05 17:58
Ok... Does your mod cause it?

**Comment by joe-vettek** [comment] 2023-02-05 18:01
and it also shows that the before efforts isn't meaningless.
Tomorrow I'll continue to fix the  remaining bugs.

**Comment by DragonMaster14545** [comment] 2023-02-05 18:02
Thanks a lot

**Comment by joe-vettek** [comment] 2023-02-05 18:04
> Ok... Does your mod cause it? 

I think so, I'm actually surprised that create even accesses that function.

**Comment by joe-vettek** [comment] 2023-02-05 18:09
Tomorrow I'll check all related functions and fix others may causing crash, currently all crashes are caused by the controller, which is determined by its caching mechanism.

**Comment by joe-vettek** [comment] 2023-02-06 04:26
![image](https://user-images.githubusercontent.com/82761814/216883509-25102527-d954-4696-949d-4601ab75e011.png)

test for a while, no crash happens

**Comment by joe-vettek** [comment] 2023-02-06 04:27
you can try the latest beta version

**Comment by DragonMaster14545** [comment] 2023-02-06 05:26
Ill do thanks, btw it ran good for to days so...

**Comment by DragonMaster14545** [comment] 2023-02-06 05:33
I got this crash in the night https://pastebin.com/tRt6TXuv

**Comment by joe-vettek** [comment] 2023-02-06 09:46
you need use the latest 2.3.3-beta and now the version you use is 2.3.2-fix. sorry I don't say it clearly.

https://beta.curseforge.com/minecraft/mc-mods/fluid-drawers-legacy/files/4382751

**Comment by DragonMaster14545** [comment] 2023-02-06 10:31
Ok ill try that thanks

**Comment by DragonMaster14545** [comment] 2023-02-06 18:50
I have the latest beta version installed and just got this
https://pastebin.com/iJfNUSbW
Sorry for beeing so annoying

**Comment by joe-vettek** [comment] 2023-02-07 15:35
FluidDrawersLegacy-1.18.2-forge-2.3.4-beta.jar

**Comment by joe-vettek** [comment] 2023-02-07 15:39
https://github.com/joe-vettek/Fluid-Drawers-Legacy/releases/tag/test

**Comment by joe-vettek** [comment] 2023-02-07 18:56
By the way, I found another bug, which was fixed after checking. So version 2.3.5 was released.
https://www.curseforge.com/minecraft/mc-mods/fluid-drawers-legacy/files/4385815

**Comment by joe-vettek** [comment] 2023-02-07 19:16
The null pointer problem is due to the architecture, the caching mechanism requires that the drawer index collection be updated every five seconds (this is consistent with the storage drawer mod). In the old version, the update is completed by clearing the previous drawer index set and then adding the drawer index again. The new version first checks whether the old and new index sets are identical before considering whether to directly replace the entire index set.
In addition, the rebuilt lock has also been updated (it is responsible for finally judging whether index updates can be performed), all adjusted to semaphores instead of boolean locks that are prone to failure during multi-threaded access.

**Comment by joe-vettek** [comment] 2023-02-07 19:32
The final defense plan is to use try catch, but this is a more irresponsible way of writing, so I will not consider this. Thank you for your patience. It is difficult for developers to determine the cause of this hidden error

**Comment by DragonMaster14545** [comment] 2023-02-07 20:17
Thanks for investing so much time in fixing my problem

**Closed as completed** 2023-02-28 12:01 UTC
Labels: bug, fixed
